package tools;

/**
 * Created by user on 19/03/18.
 */

public class Constantes {

   private static String[][] countryCode =
            {

                    {"DZA","Africa","DZ","Algeria"},
                    {"AGO","Africa","AO","Angola"},
                    {"ASC","Africa","AC","Ascension Island"},
                    {"BEN","Africa","BJ","Benin"},
                    {"BWA","Africa","BW","Botswana"},
                    {"BFA","Africa","BF","Burkina Faso"},
                    {"BDI","Africa","BI","Burundi"},
                    {"CMR","Africa","CM","Cameroon"},
                    {"CPV","Africa","CV","Cape Verde"},
                    {"CAF","Africa","CF","Central African Republic"},
                    {"TCD","Africa","TD","Chad"},
                    {"COM","Africa","KM","Comoros"},
                    {"COG","Africa","CG","Congo"},
                    {"COD","Africa","CD","Congo, The Democratic Republic Of The"},
                    {"CIV","Africa","CI","CÔte D'ivoire"},
                    {"DGA","Africa","DG","Diego Garcia"},
                    {"DJI","Africa","DJ","Djibouti"},
                    {"EGY","Africa","EG","Egypt"},
                    {"GNQ","Africa","GQ","Equatorial Guinea"},
                    {"ERI","Africa","ER","Eritrea"},
                    {"ETH","Africa","ET","Ethiopia"},
                    {"FLK","Africa","FK","Falkland Islands (malvinas)"},
                    {"GAB","Africa","GA","Gabon"},
                    {"GHA","Africa","GH","Ghana"},
                    {"GIB","Africa","GI","Gibraltar"},
                    {"GIN","Africa","GN","Guinea"},
                    {"GNB","Africa","GW","Guinea-Bissau"},
                    {"KEN","Africa","KE","Kenya"},
                    {"LSO","Africa","LS","Lesotho"},
                    {"LBR","Africa","LR","Liberia"},
                    {"LBY","Africa","LY","Libya"},
                    {"MDG","Africa","MG","Madagascar"},
                    {"MWI","Africa","MW","Malawi"},
                    {"MLI","Africa","ML","Mali"},
                    {"MRT","Africa","MR","Mauritania"},
                    {"MUS","Africa","MU","Mauritius"},
                    {"MYT","Africa","YT","Mayotte"},
                    {"MAR","Africa","MA","Morocco"},
                    {"MOZ","Africa","MZ","Mozambique"},
                    {"NAM","Africa","NA","Namibia"},
                    {"NER","Africa","NE","Niger"},
                    {"NGA","Africa","NG","Nigeria"},
                    {"REU","Africa","RE","RÉunion"},
                    {"RWA","Africa","RW","Rwanda"},
                    {"SHN","Africa","SH","Saint Helena"},
                    {"STP","Africa","ST","Sao Tome And Principe"},
                    {"SEN","Africa","SN","Senegal"},
                    {"SYC","Africa","SC","Seychelles"},
                    {"SLE","Africa","SL","Sierra Leone"},
                    {"SOM","Africa","SO","Somalia"},
                    {"ZAF","Africa","ZA","South Africa"},
                    {"SDN","Africa","SD","Sudan"},
                    {"SWZ","Africa","SZ","Swaziland"},
                    {"TZA","Africa","TZ","Tanzania, United Republic Of"},
                    {"GMB","Africa","GM","The Gambia"},
                    {"TGO","Africa","TG","Togo"},
                    {"TAA","Africa","TA","Tristan da Cunha"},
                    {"TUN","Africa","TN","Tunisia"},
                    {"UGA","Africa","UG","Uganda"},
                    {"ESH","Africa","EH","Western Sahara"},
                    {"ZMB","Africa","ZM","Zambia"},
                    {"ZWE","Africa","ZW","Zimbabwe"},
                    {"ATA","Antarctica","AQ","Antarctica"},
                    {"BVT","Antarctica","BV","Bouvet Island"},
                    {"ATF","Antarctica","TF","French Southern Territories"},
                    {"AFG","Asia","AF","Afghanistan"},
                    {"ARM","Asia","AM","Armenia"},
                    {"AZE","Asia","AZ","Azerbaijan"},
                    {"BHR","Asia","BH","Bahrain"},
                    {"BGD","Asia","BD","Bangladesh"},
                    {"BTN","Asia","BT","Bhutan"},
                    {"IOT","Asia","IO","British Indian Ocean Territory"},
                    {"BRN","Asia","BN","Brunei Darussalam"},
                    {"MMR","Asia","MM","Burma"},
                    {"KHM","Asia","KH","Cambodia"},
                    {"CHN","Asia","CN","China"},
                    {"CXR","Asia","CX","Christmas Island"},
                    {"CCK","Asia","CC","Cocos (keeling) Islands"},
                    {"CYP","Asia","CY","Cyprus"},
                    {"GUM","Asia","GU","Guam"},
                    {"HKG","Asia","HK","Hong Kong"},
                    {"IND","Asia","IN","India"},
                    {"IDN","Asia","ID","Indonesia"},
                    {"IRN","Asia","IR","Iran"},
                    {"IRQ","Asia","IQ","Iraq"},
                    {"ISR","Asia","IL","Israel"},
                    {"JPN","Asia","JP","Japan"},
                    {"JOR","Asia","JO","Jordan"},
                    {"KAZ","Asia","KZ","Kazakhstan"},
                    {"KWT","Asia","KW","Kuwait"},
                    {"KGZ","Asia","KG","Kyrgyzstan"},
                    {"LAO","Asia","LA","Lao People's Democratic Republic"},
                    {"LBN","Asia","LB","Lebanon"},
                    {"MAC","Asia","MO","Macao"},
                    {"MYS","Asia","MY","Malaysia"},
                    {"MDV","Asia","MV","Maldives"},
                    {"MNG","Asia","MN","Mongolia"},
                    {"NPL","Asia","NP","Nepal"},
                    {"PRK","Asia","KP","North Korea"},
                    {"OMN","Asia","OM","Oman"},
                    {"PAK","Asia","PK","Pakistan"},
                    {"PSE","Asia","PS","Palestinian Territory, Occupied"},
                    {"PHL","Asia","PH","Philippines"},
                    {"QAT","Asia","QA","Qatar"},
                    {"RUS","Asia","RU","Russian Federation"},
                    {"SAU","Asia","SA","Saudi Arabia"},
                    {"NTZ","Asia","NT","Saudi–Iraqi neutral zone"},
                    {"SGP","Asia","SG","Singapore"},
                    {"KOR","Asia","KR","South Korea"},
                    {"LKA","Asia","LK","Sri Lanka"},
                    {"SYR","Asia","SY","Syrian Arab Republic"},
                    {"TWN","Asia","TW","Taiwan"},
                    {"TJK","Asia","TJ","Tajikistan"},
                    {"THA","Asia","TH","Thailand"},
                    {"TUR","Asia","TR","Turkey"},
                    {"TKM","Asia","TM","Turkmenistan"},
                    {"ARE","Asia","AE","United Arab Emirates"},
                    {"UZB","Asia","UZ","Uzbekistan"},
                    {"VNM","Asia","VN","Viet Nam"},
                    {"YEM","Asia","YE","Yemen"},
                    {"ASM","Australia","AS","American Samoa"},
                    {"AUS","Australia","AU","Australia"},
                    {"COK","Australia","CK","Cook Islands"},
                    {"TLS","Australia","TL","East Timor"},
                    {"FJI","Australia","FJ","Fiji"},
                    {"PYF","Australia","PF","French Polynesia"},
                    {"HMD","Australia","HM","Heard Island And Mcdonald Islands"},
                    {"KIR","Australia","KI","Kiribati"},
                    {"MHL","Australia","MH","Marshall Islands"},
                    {"FSM","Australia","FM","Micronesia, Federated States Of"},
                    {"NRU","Australia","NR","Nauru"},
                    {"NCL","Australia","NC","New Caledonia"},
                    {"NZL","Australia","NZ","New Zealand"},
                    {"NIU","Australia","NU","Niue"},
                    {"NFK","Australia","NF","Norfolk Island"},
                    {"MNP","Australia","MP","Northern Mariana Islands"},
                    {"PLW","Australia","PW","Palau"},
                    {"PNG","Australia","PG","Papua New Guinea"},
                    {"PCN","Australia","PN","Pitcairn"},
                    {"WSM","Australia","WS","Samoa"},
                    {"SLB","Australia","SB","Solomon Islands"},
                    {"TKL","Australia","TK","Tokelau"},
                    {"TON","Australia","TO","Tonga"},
                    {"TUV","Australia","TV","Tuvalu"},
                    {"VUT","Australia","VU","Vanuatu"},
                    {"WLF","Australia","WF","Wallis And Futuna"},
                    {"ALA","Europe","AX","Åland Islands"},
                    {"ALB","Europe","AL","Albania"},
                    {"AND","Europe","AD","Andorra"},
                    {"AUT","Europe","AT","Austria"},
                    {"BLR","Europe","BY","Belarus"},
                    {"BEL","Europe","BE","Belgium"},
                    {"BIH","Europe","BA","Bosnia And Herzegovina"},
                    {"BGR","Europe","BG","Bulgaria"},
                    {"","Europe","IC","Canary Islands"},
                    {"HRV","Europe","HR","Croatia"},
                    {"CZE","Europe","CZ","Czech Republic"},
                    {"DNK","Europe","DK","Denmark"},
                    {"EST","Europe","EE","Estonia"},
                    {"","Europe","EU","European Union"},
                    {"FRO","Europe","FO","Faroe Islands"},
                    {"FIN","Europe","FI","Finland"},
                    {"FRA","Europe","FR","France"},
                    {"GEO","Europe","GE","Georgia"},
                    {"DEU","Europe","DE","Germany"},
                    {"GRC","Europe","GR","Greece"},
                    {"GGY","Europe","GG","Guernsey"},
                    {"HUN","Europe","HU","Hungary"},
                    {"ISL","Europe","IS","Iceland"},
                    {"IRL","Europe","IE","Ireland"},
                    {"IMN","Europe","IM","Isle Of Man"},
                    {"ITA","Europe","IT","Italy"},
                    {"JEY","Europe","JE","Jersey"},
                    {"LVA","Europe","LV","Latvia"},
                    {"LIE","Europe","LI","Liechtenstein"},
                    {"LTU","Europe","LT","Lithuania"},
                    {"LUX","Europe","LU","Luxembourg"},
                    {"MLT","Europe","MT","Malta"},
                    {"MDA","Europe","MD","Moldova"},
                    {"MCO","Europe","MC","Monaco"},
                    {"MNE","Europe","ME","Montenegro"},
                    {"NLD","Europe","NL","Netherlands"},
                    {"NOR","Europe","NO","Norway"},
                    {"POL","Europe","PL","Poland"},
                    {"PRT","Europe","PT","Portugal"},
                    {"MKD","Europe","MK","Republic of Macedonia"},
                    {"ROU","Europe","RO","Romania"},
                    {"SMR","Europe","SM","San Marino"},
                    {"SRB","Europe","RS","Serbia"},
                    {"SCG","Europe","CS","Serbia and Montenegro"},
                    {"SVK","Europe","SK","Slovakia"},
                    {"SVN","Europe","SI","Slovenia"},
                    {"SUN","Europe","SU","Soviet Union"},
                    {"ESP","Europe","ES","Spain"},
                    {"SJM","Europe","SJ","Svalbard And Jan Mayen"},
                    {"SWE","Europe","SE","Sweden"},
                    {"CHE","Europe","CH","Switzerland"},
                    {"UKR","Europe","UA","Ukraine"},
                    {"GBR","Europe","GB","United Kingdom"},
                    {"VAT","Europe","VA","Vatican City"},
                    {"AIA","North America","AI","Anguilla"},
                    {"ATG","North America","AG","Antigua And Barbuda"},
                    {"ABW","North America","AW","Aruba"},
                    {"BHS","North America","BS","Bahamas"},
                    {"BRB","North America","BB","Barbados"},
                    {"BLZ","North America","BZ","Belize"},
                    {"BMU","North America","BM","Bermuda"},
                    {"VGB","North America","VG","British Virgin Islands"},
                    {"CAN","North America","CA","Canada"},
                    {"CYM","North America","KY","Cayman Islands"},
                    {"CRI","North America","CR","Costa Rica"},
                    {"CUB","North America","CU","Cuba"},
                    {"DMA","North America","DM","Dominica"},
                    {"SLV","North America","SV","El Salvador"},
                    {"GRL","North America","GL","Greenland"},
                    {"GRD","North America","GD","Grenada"},
                    {"GLP","North America","GP","Guadeloupe"},
                    {"GTM","North America","GT","Guatemala"},
                    {"HTI","North America","HT","Haiti"},
                    {"HND","North America","HN","Honduras"},
                    {"JAM","North America","JM","Jamaica"},
                    {"MTQ","North America","MQ","Martinique"},
                    {"MEX","North America","MX","Mexico"},
                    {"MSR","North America","MS","Montserrat"},
                    {"ANT","North America","AN","Netherlands Antilles"},
                    {"NIC","North America","NI","Nicaragua"},
                    {"PRI","North America","PR","Puerto Rico"},
                    {"KNA","North America","KN","Saint Kitts And Nevis"},
                    {"SPM","North America","PM","Saint Pierre And Miquelon"},
                    {"TCA","North America","TC","Turks And Caicos Islands"},
                    {"USA","North America","US","United States"},
                    {"ARG","South America","AR","Argentina"},
                    {"BOL","South America","BO","Bolivia"},
                    {"BRA","South America","BR","Brazil"},
                    {"CHL","South America","CL","Chile"},
                    {"COL","South America","CO","Colombia"},
                    {"DOM","South America","DO","Dominican Republic"},
                    {"ECU","South America","EC","Ecuador"},
                    {"GUF","South America","GF","French Guiana"},
                    {"GUY","South America","GY","Guyana"},
                    {"PAN","South America","PA","Panama"},
                    {"PRY","South America","PY","Paraguay"},
                    {"PER","South America","PE","Peru"},
                    {"LCA","South America","LC","Saint Lucia"},
                    {"VCT","South America","VC","Saint Vincent and the Grenadines"},
                    {"SGS","South America","GS","South Georgia And The South Sandwich Islands"},
                    {"SUR","South America","SR","Suriname"},
                    {"TTO","South America","TT","Trinidad And Tobago"},
                    {"URY","South America","UY","Uruguay"},
                    {"VEN","South America","VE","Venezuela"},
                    {"VIR","South America","VI","Virgin Islands, U.s."}
                    
            };


        public static String getCountryName(String codeiso3)
        {

           String nameCountry ="";
           int sizeCountryCode = countryCode.length;

           for (int i = 0 ; i < sizeCountryCode; i++)
           {
               String cC =countryCode[i][0] ;
               if (cC.equalsIgnoreCase(codeiso3) )
               {
                   nameCountry = countryCode[i][3];
               }
           }



            return nameCountry;
        }
}
